### ISSUE TITLE
Usage documentation 

### ISSUE THREAD

**Issue by robdefeo** [roycehaynes/scrapy-rabbitmq#1]
it would be great to understand how this works

**Comment by roycehaynes** [comment]
@rdefeo - I'll be making updates to docs and code soon. I'll ping you when updated.

**Comment by robdefeo** [comment]
Thanks thats great

**Comment by vivekanand1101** [comment]
@roycehaynes  this project sounds exactly what i need, but i am not able to proceed further. Can you please provide the documentation ASAP ?

**Comment by roycehaynes** [comment]
@vivekanand1101 - I'll be contributing to this project over the weekend and next week. Again, i'll give a shout here when docs and a few updates are made.

**Comment by robdefeo** [comment]
Great, thanks

**Comment by roycehaynes** [comment]
Heyo! I updated documentation in the readme. Let me know if more info is needed and I can add to the README docs. I'll also be posting a blog post as well with details very soon. Thanks for your patience.

**Comment by robdefeo** [comment]
Looks great, would this mean that the scrape could be distributed across several servers?
